# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIDemo

  target 'UIDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIDemoUITests' do
    # Pods for testing
  end
  pod 'Masonry'

end
